name: Hourly Task

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-node@v2
    #   - name: Run Project
    #     run: |
    #       yarn
    #       yarn tea
